units:
  u: 21.5
  hex_spread: "u * 0.866"

points:
  zones:
    matrix:
      key:
        spread: hex_spread
        padding: u
        footprints:
          dot:
            type: via
            anchor:
              shift: [0, 0]
      columns:
        A:
          key.stagger: 0
        B:
          key.stagger: "u / 2"
        C:
          key.stagger: "u / 2"
        D:
          key.stagger: "-u / 2"
        E:
          key.stagger: "-u / 2"
      rows:
        bottom:
        home:
        top:

    extra:
      anchor:
        ref: matrix_E_top
        shift: [hex_spread, -u / 2]
      key:
        spread: hex_spread
        padding: u
        footprints:
          dot:
            type: pad
            nets:
              "1": GND
            params:
              side: F.Cu
              shape: circle
              width: 1
              height: 1
      columns:
        only:
      rows:
        only:

    thumb:
      anchor:
        ref: matrix_E_bottom
        shift: [hex_spread, -u*1.5]
      key:
        spread: hex_spread
        padding: u
        footprints:
          dot:
            type: pad
            nets:
              "1": GND
            params:
              side: F.Cu
              shape: circle
              width: 1
              height: 1
      columns:
        left:
          key.stagger: 0
        mid:
          key.stagger: "u / 2"
        right:
          key.stagger: "-u / 2"
      rows:
        only:

    power:
      anchor:
        ref: matrix_E_top
        shift: ["hex_spread * 3", -u / 2]
      key:
        spread: hex_spread
        padding: u
        footprints:
          dot:
            type: pad
            nets:
              "1": GND
            params:
              side: F.Cu
              shape: circle
              width: 1
              height: 1
      columns:
        only:
      rows:
        only:

pcbs:
  demo: 
    template: kicad8
    footprints:
      pos:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"